### ISSUE TITLE
UnicodeDecodeError in windows 

### ISSUE THREAD

**Issue by Crispae** [indralab/pybiopax#50]
Hi,

I am loading the kegg  pathway  from pathway commons, but it give issue of unidecodeError on windows, while it works fine on linux.

![image](https://github.com/gyorilab/pybiopax/assets/74324530/680fe61b-deab-4975-a469-21b85aeeeb61)

**Comment by Crispae** [comment]
version 0.1.4

**Comment by cthoyt** [comment]
If you're on windows, this might be because `gzip.open` picks an unexpected default encoding. We can try allowing passing through the encoding to 

https://github.com/gyorilab/pybiopax/blob/6d290f5e6850e053fb69379f46e93e968b022673/pybiopax/api.py#L72-L73

And see if this solves it. Can you try doing the following:

```python
import gzip
from lxml import etree
from pybiopax.biopax import BioPaxModel

encoding = 'utf-8'

with gzip.open(path, 'rt', encoding=encoding) as fh:
    model = BioPaxModel.from_xml(etree.parse(fh).getroot())
```

I wonder if utf-8 does it, or some other encoding would fix the issue (IIRC 0x81 is a UTF byte order mark (BOM) and there might be a different encoding that handles this)

**Comment by Crispae** [comment]
Thanks @cthoyt ,it works with utf-8 encoding, this issue occurs with other tools as having dependency on pybiopax, I guess this solution will work for them as well.
